language: php

sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.0
          env: COMPOSER_FLAGS='--prefer-lowest'
        - php: hhvm

before_install: if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: vendor/bin/phpunit

notifications:
    email: false
